baseURL: "https://devopswith6.github.io/"
languageCode: "en-us"
title: "DevOps Notes by 6"
theme: "PaperMod"

params:
  profileMode:
    enabled: true
    title: "DevOps Notes"
    subtitle: "Real-world DevOps, Kubernetes, Linux, CI/CD"

